[package]
name = "pattern_search"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.8", features = ["derive"] }
anyhow = "1.0"
indicatif = "0.17.8"
log = "0.4.22"
env_logger = "0.9"